#!/command/with-contenv sh
sleep 2
cd /data
PARAMS=
[ "${ENCRYPTED_ONLY}" = "1" ] && PARAMS="-k _"
# Automatic geo database updates keep the file at this path unless told otherwise.
[ "${GEO_AUTO_UPDATE}" = "Y" ] && [ -z "${GEO_DB}" ] && export GEO_DB=/data/geo.mmdb
/usr/bin/hbbs -r $RELAY $PARAMS
